services:
  back:
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - back
    links:
      - back
